#!/bin/bash
# Local development setup script for Baby Diary API
# Uses OIDC/AssumeRole for secure credential management

set -e

echo "========================================"
echo "Baby Diary API - Local Development Setup"
echo "========================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if aliyun CLI is installed
check_aliyun_cli() {
    if ! command -v aliyun &> /dev/null; then
        echo -e "${YELLOW}Aliyun CLI not found. Installing...${NC}"
        if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install aliyun-cli
        elif [[ "$OSTYPE" == "linux"* ]]; then
            wget -q https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz
            tar -xzf aliyun-cli-linux-latest-amd64.tgz
            sudo mv aliyun /usr/local/bin/
            rm aliyun-cli-linux-latest-amd64.tgz
        else
            echo -e "${RED}Please install aliyun CLI manually: https://help.aliyun.com/document_detail/139508.html${NC}"
            exit 1
        fi
    fi
    echo -e "${GREEN}✓ Aliyun CLI installed: $(aliyun version)${NC}"
}

# Configure credentials using browser login
configure_browser_login() {
    echo ""
    echo "Configuring Aliyun credentials via browser login..."
    echo "This will open your browser for authentication."
    echo ""

    aliyun configure --mode Browser

    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Credentials configured successfully${NC}"
    else
        echo -e "${RED}✗ Failed to configure credentials${NC}"
        exit 1
    fi
}

# Get temporary credentials via AssumeRole
assume_developer_role() {
    local ROLE_ARN="${1:-}"
    local SESSION_NAME="local-dev-$(whoami)-$(date +%Y%m%d%H%M%S)"

    if [ -z "$ROLE_ARN" ]; then
        # Try to get role ARN from terraform output
        if [ -f "terraform/terraform.tfstate" ]; then
            ROLE_ARN=$(terraform output -raw developer_role_arn 2>/dev/null || echo "")
        fi
    fi

    if [ -z "$ROLE_ARN" ]; then
        echo -e "${YELLOW}Developer role ARN not found.${NC}"
        echo "Please provide the role ARN:"
        echo "  export DEVELOPER_ROLE_ARN=acs:ram::ACCOUNT_ID:role/baby-diary-developer"
        return 1
    fi

    echo ""
    echo "Assuming developer role: $ROLE_ARN"
    echo "Session name: $SESSION_NAME"
    echo ""

    # Get temporary credentials
    local RESULT=$(aliyun sts AssumeRole \
        --RoleArn "$ROLE_ARN" \
        --RoleSessionName "$SESSION_NAME" \
        --DurationSeconds 3600 \
        --output cols=AccessKeyId,AccessKeySecret,SecurityToken,Expiration)

    if [ $? -eq 0 ]; then
        # Parse and export credentials
        local AK_ID=$(echo "$RESULT" | awk 'NR==2 {print $1}')
        local AK_SECRET=$(echo "$RESULT" | awk 'NR==2 {print $2}')
        local TOKEN=$(echo "$RESULT" | awk 'NR==2 {print $3}')
        local EXPIRATION=$(echo "$RESULT" | awk 'NR==2 {print $4}')

        export ALICLOUD_ACCESS_KEY="$AK_ID"
        export ALICLOUD_SECRET_KEY="$AK_SECRET"
        export ALICLOUD_SECURITY_TOKEN="$TOKEN"

        echo -e "${GREEN}✓ Temporary credentials obtained${NC}"
        echo "  Expiration: $EXPIRATION"
        echo ""
        echo "Credentials exported to environment variables:"
        echo "  ALICLOUD_ACCESS_KEY (set)"
        echo "  ALICLOUD_SECRET_KEY (set)"
        echo "  ALICLOUD_SECURITY_TOKEN (set)"
    else
        echo -e "${RED}✗ Failed to assume role${NC}"
        return 1
    fi
}

# Setup local environment file
setup_env_file() {
    echo ""
    echo "Setting up local environment..."

    if [ ! -f ".env.local" ]; then
        echo "Creating .env.local from .env.example..."

        # Get infrastructure info from terraform
        if [ -f "terraform/terraform.tfstate" ]; then
            local VPC_ID=$(terraform output -raw vpc_id 2>/dev/null || echo "")
            local VSWITCH_ID=$(terraform output -raw vswitch_id 2>/dev/null || echo "")
            local SG_ID=$(terraform output -raw security_group_id 2>/dev/null || echo "")
            local DB_HOST=$(terraform output -raw db_host 2>/dev/null || echo "")

            cat > .env.local << EOF
# Local development environment
# Generated by scripts/setup_local_dev.sh

DATABASE_URL=postgresql://baby_diary:password@${DB_HOST}:5432/baby_diary
VPC_ID=${VPC_ID}
VSWITCH_ID=${VSWITCH_ID}
SECURITY_GROUP_ID=${SG_ID}

# These will be loaded from OSS at runtime
OSS_SECRETS_BUCKET=baby-diary-secrets
OSS_ENDPOINT=oss-cn-hangzhou.aliyuncs.com

# Development settings
DEBUG=true
JWT_SECRET=dev-jwt-secret-change-in-production
EOF
            echo -e "${GREEN}✓ Created .env.local${NC}"
        else
            echo -e "${YELLOW}Terraform state not found. Please run 'terraform apply' first.${NC}"
        fi
    else
        echo -e "${GREEN}✓ .env.local already exists${NC}"
    fi
}

# Main menu
show_menu() {
    echo ""
    echo "Choose an option:"
    echo "  1) Configure via browser login (recommended)"
    echo "  2) Assume developer role (requires MFA)"
    echo "  3) Setup environment file"
    echo "  4) Full setup (all of the above)"
    echo "  5) Exit"
    echo ""
}

# Main
main() {
    check_aliyun_cli

    if [ "${1:-}" != "" ]; then
        case "$1" in
            browser)
                configure_browser_login
                ;;
            assume-role)
                assume_developer_role "${2:-}"
                ;;
            env)
                setup_env_file
                ;;
            full)
                configure_browser_login
                assume_developer_role
                setup_env_file
                ;;
            *)
                echo "Usage: $0 {browser|assume-role|env|full}"
                exit 1
                ;;
        esac
        exit 0
    fi

    # Interactive mode
    while true; do
        show_menu
        read -p "Enter choice: " choice

        case $choice in
            1)
                configure_browser_login
                ;;
            2)
                assume_developer_role
                ;;
            3)
                setup_env_file
                ;;
            4)
                configure_browser_login
                assume_developer_role
                setup_env_file
                ;;
            5)
                echo "Goodbye!"
                exit 0
                ;;
            *)
                echo -e "${RED}Invalid option${NC}"
                ;;
        esac
    done
}

main "$@"